### ISSUE TITLE
Problem configure template memex

### ISSUE THREAD

**Issue by kevinlupera** [victoriadrake/hugo-theme-memex#1]
**Describe the bug**
I have problems to use the template, I made the indicated configurations but they don't show me the posts in the home page. If it would be possible to add an example to be able to use it.

**To Reproduce**
1. Create a project hugo.
2. Configure template memex.
3. Add posts

**Expected behavior**
I should be able to show the posts when adding content but it doesn't show me anything.

**Screenshots**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/11479964/191384577-fb7eb1e5-00c5-49b4-94b1-f0e064602f78.png">

OS: MacOs 10.15.7
Browser: Chrome
Version: 108.0.5311.0

**Smartphone (please complete the following information):**

Device: Xiaomi MI A3
OS: Android 11
Browser chrome
Version latest

**Additional context**
No additional context is needed I believe. I really liked your work and I consider that the functionalities used in the template I did not find in other templates.

**Comment by victoriadrake** [comment]
Hello Kevin! If you are still experiencing this issue, can you link your site repository (if it is public) or share your folder structure? (You can do `tree` in a terminal to see it.)

**Comment by kevinlupera** [comment]
Hello Victoria, thanks for you answer, you are amazing, I really like the way you explain in your blog that inspired me to create one of my own.
[https://github.com/kevinlupera/blog-personal-memex](https://github.com/kevinlupera/blog-personal-memex)
<img width="280" alt="image" src="https://user-images.githubusercontent.com/11479964/223615999-430f8a89-8b8d-462f-8c69-173a442dc3d0.png">

**Comment by victoriadrake** [comment]
Hi Kevin, I think this is happening for two reasons:

1. Your [post](https://github.com/kevinlupera/blog-personal-memex/blob/main/content/posts/my-first-post.md) has `draft: true` in the front matter (see https://gohugo.io/getting-started/usage/#draft-future-and-expired-content)
2. Your post has no content. Try writing something in the post body (below the front matter).

Hope this helps!
